export const defaultAppSettings = {
  darkTheme: false,
  appLanguage: "en",
  audioLanguage: "en",
  supportLanguage: "en",
  orderAlertSound: "classic",
}

export const languageOptions = [
  { value: "en", label: "English" },
  { value: "hi", label: "Hindi" },
  { value: "or", label: "Odia" },
]

export const soundOptions = [
  { value: "classic", label: "Classic bell", frequency: 880 },
  { value: "soft", label: "Soft chime", frequency: 660 },
  { value: "urgent", label: "Urgent alert", frequency: 1040 },
  { value: "silent", label: "Silent", frequency: 0 },
]

export const toDashboardSettings = (account) => {
  if (!account) return defaultAppSettings
  return {
    darkTheme: Boolean(account.dark_theme),
    appLanguage: account.app_language || "en",
    audioLanguage: account.audio_language || "en",
    supportLanguage: account.support_language || "en",
    orderAlertSound: account.order_alert_sound || "classic",
  }
}

export const toApiSettings = (settings) => ({
  dark_theme: Boolean(settings.darkTheme),
  app_language: settings.appLanguage,
  audio_language: settings.audioLanguage,
  support_language: settings.supportLanguage,
  order_alert_sound: settings.orderAlertSound,
})

export const applyAppSettings = (settings = defaultAppSettings) => {
  document.documentElement.classList.toggle("dark", Boolean(settings.darkTheme))
  document.documentElement.lang = settings.appLanguage || "en"
}

export const dashboardText = {
  en: {
    overview: "Overview",
    myBookings: "My Bookings",
    bookings: "Bookings",
    favorites: "Favorites",
    messages: "Messages",
    notifications: "Notifications",
    payments: "Payments",
    profile: "Profile",
    settings: "Settings",
    services: "Services",
    reviews: "Reviews",
    wallet: "Wallet",
    analytics: "Analytics",
    helpSupport: "Help & Support",
    logOut: "Log Out",
    logout: "Logout",
    customerAccount: "Customer Account",
    vendorAccount: "Vendor Account",
    search: "Search...",
    searchBookings: "Search bookings...",
    settingsDescription: "Manage app appearance, languages, alerts, and account access.",
    appSettings: "App settings",
    darkTheme: "Dark theme",
    appLanguage: "App language",
    audioLanguage: "Audio language",
    supportLanguage: "Support language",
    orderAlertSound: "Order alert sound",
    testAlertSound: "Test alert sound",
    resetSettings: "Reset settings",
    settingsSaved: "Settings saved.",
    settingsReset: "Settings reset.",
    helpTitle: "Help & Support",
    helpDescription: "Contact BookMyEvent support for booking, payment, or account help.",
    phone: "Phone",
    email: "Email",
    totalBookings: "Total Bookings",
    activeOrders: "Active Orders",
    reviewsGiven: "Reviews Given",
    browseVendors: "Browse Vendors",
    hi: "Hi",
    customer: "Customer",
    vendor: "Vendor",
    yourOrders: "Your Orders",
    viewAll: "View All",
    loadingOrders: "Loading orders...",
    noOrdersDashboard: "No orders yet. Book a vendor to see it here.",
    recommendedVendors: "Recommended Vendors",
    myOrders: "My Orders",
    ordersDescription: "Track booking requests, confirmations, and remaining payments.",
    unableLoadOrders: "Unable to load orders.",
    vendorContactShared: "Vendor contact shared after full payment",
    remainingDue: "Remaining due",
    vendorAcceptedPay48: "Vendor accepted your request. Cancellation is closed now; pay within 48 hours or advance is non-refundable.",
    timeLeft: "Time left",
    payRemaining: "Pay Remaining",
    withRazorpay: "with Razorpay",
    cancelBeforeAccept: "You can cancel before vendor accepts. Your advance refund will be initiated after cancellation.",
    selectCancellationReason: "Select cancellation reason",
    close: "Close",
    cancelling: "Cancelling...",
    confirmCancel: "Confirm Cancel",
    cancelBookingRefund: "Cancel Booking & Refund",
    noOrders: "No orders yet.",
    bookedByMistake: "Booked by mistake",
    eventDateChanged: "Event date changed",
    foundAnotherVendor: "Found another vendor",
    budgetIssue: "Budget issue",
    noLongerRequired: "No longer required",
    expired: "Expired",
    favoritesDescription: "Vendors you saved for quick booking.",
    loadingFavorites: "Loading favorites...",
    remove: "Remove",
    noFavorites: "No favorites yet. Open a vendor and save it from the heart button.",
    messagesDescription: "Send a support message directly to admin.",
    messageToAdmin: "Message to admin",
    writeQuestion: "Write your question or issue...",
    sending: "Sending...",
    sendMessage: "Send Message",
    messageSent: "Message sent to admin.",
    unableSendMessage: "Unable to send message.",
    notificationsDescription: "Booking and payment updates appear here.",
    loadingNotifications: "Loading notifications...",
    noNotifications: "No notifications yet.",
    paymentsDescription: "Advance, remaining, and refund records.",
    loadingPayments: "Loading payments...",
    noPayments: "No payments yet.",
    updateCustomerDetails: "Update customer details and profile photo.",
    updateDp: "Update DP",
    captureProfilePhoto: "Capture and save a live profile photo.",
    retake: "Retake",
    savePhoto: "Save Photo",
    saving: "Saving...",
    saveProfile: "Save Profile",
    name: "Name",
    phoneLabel: "Phone",
    profileSaved: "Profile saved successfully.",
    profilePhotoUpdated: "Profile photo updated successfully.",
    unableSaveProfile: "Unable to save profile.",
    unableUpdatePhoto: "Unable to update profile photo.",
  },
  hi: {
    overview: "अवलोकन",
    myBookings: "मेरी बुकिंग",
    bookings: "बुकिंग",
    favorites: "पसंदीदा",
    messages: "संदेश",
    notifications: "सूचनाएं",
    payments: "भुगतान",
    profile: "प्रोफाइल",
    settings: "सेटिंग्स",
    services: "सेवाएं",
    reviews: "समीक्षाएं",
    wallet: "वॉलेट",
    analytics: "एनालिटिक्स",
    helpSupport: "सहायता और समर्थन",
    logOut: "लॉग आउट",
    logout: "लॉग आउट",
    customerAccount: "ग्राहक खाता",
    vendorAccount: "विक्रेता खाता",
    search: "खोजें...",
    searchBookings: "बुकिंग खोजें...",
    settingsDescription: "ऐप रूप, भाषा, अलर्ट और खाते की पहुंच प्रबंधित करें.",
    appSettings: "ऐप सेटिंग्स",
    darkTheme: "डार्क थीम",
    appLanguage: "ऐप भाषा",
    audioLanguage: "ऑडियो भाषा",
    supportLanguage: "सपोर्ट भाषा",
    orderAlertSound: "ऑर्डर अलर्ट साउंड",
    testAlertSound: "अलर्ट साउंड टेस्ट करें",
    resetSettings: "सेटिंग्स रीसेट करें",
    settingsSaved: "सेटिंग्स सेव हो गई.",
    settingsReset: "सेटिंग्स रीसेट हो गई.",
    helpTitle: "सहायता और समर्थन",
    helpDescription: "बुकिंग, भुगतान या खाते की मदद के लिए BookMyEvent सपोर्ट से संपर्क करें.",
    phone: "फोन",
    email: "ईमेल",
    totalBookings: "कुल बुकिंग",
    activeOrders: "सक्रिय ऑर्डर",
    reviewsGiven: "दी गई समीक्षाएं",
    browseVendors: "वेंडर देखें",
    hi: "नमस्ते",
    customer: "ग्राहक",
    vendor: "वेंडर",
    yourOrders: "आपके ऑर्डर",
    viewAll: "सभी देखें",
    loadingOrders: "ऑर्डर लोड हो रहे हैं...",
    noOrdersDashboard: "अभी कोई ऑर्डर नहीं. वेंडर बुक करें और यहां देखें.",
    recommendedVendors: "सुझाए गए वेंडर",
    myOrders: "मेरे ऑर्डर",
    ordersDescription: "बुकिंग अनुरोध, पुष्टि और बाकी भुगतान ट्रैक करें.",
    unableLoadOrders: "ऑर्डर लोड नहीं हो पाए.",
    vendorContactShared: "पूरा भुगतान होने के बाद वेंडर संपर्क साझा किया गया",
    remainingDue: "बाकी भुगतान",
    vendorAcceptedPay48: "वेंडर ने आपका अनुरोध स्वीकार किया है. अब रद्दीकरण बंद है; 48 घंटे में भुगतान करें, नहीं तो एडवांस नॉन-रिफंडेबल होगा.",
    timeLeft: "समय बचा",
    payRemaining: "बाकी भुगतान करें",
    withRazorpay: "Razorpay से",
    cancelBeforeAccept: "वेंडर स्वीकार करने से पहले आप रद्द कर सकते हैं. रद्द करने के बाद एडवांस रिफंड शुरू किया जाएगा.",
    selectCancellationReason: "रद्द करने का कारण चुनें",
    close: "बंद करें",
    cancelling: "रद्द हो रहा है...",
    confirmCancel: "रद्दीकरण पुष्टि करें",
    cancelBookingRefund: "बुकिंग रद्द करें और रिफंड",
    noOrders: "अभी कोई ऑर्डर नहीं.",
    bookedByMistake: "गलती से बुक हुआ",
    eventDateChanged: "इवेंट तारीख बदल गई",
    foundAnotherVendor: "दूसरा वेंडर मिल गया",
    budgetIssue: "बजट समस्या",
    noLongerRequired: "अब जरूरत नहीं",
    expired: "समाप्त",
    favoritesDescription: "जल्दी बुकिंग के लिए सेव किए गए वेंडर.",
    loadingFavorites: "पसंदीदा लोड हो रहे हैं...",
    remove: "हटाएं",
    noFavorites: "अभी कोई पसंदीदा नहीं. वेंडर खोलकर हार्ट बटन से सेव करें.",
    messagesDescription: "एडमिन को सीधे सपोर्ट संदेश भेजें.",
    messageToAdmin: "एडमिन को संदेश",
    writeQuestion: "अपना सवाल या समस्या लिखें...",
    sending: "भेजा जा रहा है...",
    sendMessage: "संदेश भेजें",
    messageSent: "संदेश एडमिन को भेजा गया.",
    unableSendMessage: "संदेश भेज नहीं पाए.",
    notificationsDescription: "बुकिंग और भुगतान अपडेट यहां दिखेंगे.",
    loadingNotifications: "सूचनाएं लोड हो रही हैं...",
    noNotifications: "अभी कोई सूचना नहीं.",
    paymentsDescription: "एडवांस, बाकी और रिफंड रिकॉर्ड.",
    loadingPayments: "भुगतान लोड हो रहे हैं...",
    noPayments: "अभी कोई भुगतान नहीं.",
    updateCustomerDetails: "ग्राहक विवरण और प्रोफाइल फोटो अपडेट करें.",
    updateDp: "DP अपडेट करें",
    captureProfilePhoto: "लाइव प्रोफाइल फोटो कैप्चर करके सेव करें.",
    retake: "फिर से लें",
    savePhoto: "फोटो सेव करें",
    saving: "सेव हो रहा है...",
    saveProfile: "प्रोफाइल सेव करें",
    name: "नाम",
    phoneLabel: "फोन",
    profileSaved: "प्रोफाइल सफलतापूर्वक सेव हो गई.",
    profilePhotoUpdated: "प्रोफाइल फोटो अपडेट हो गई.",
    unableSaveProfile: "प्रोफाइल सेव नहीं हो पाई.",
    unableUpdatePhoto: "प्रोफाइल फोटो अपडेट नहीं हो पाई.",
  },
  or: {
    overview: "ସାରାଂଶ",
    myBookings: "ମୋ ବୁକିଂ",
    bookings: "ବୁକିଂ",
    favorites: "ପସନ୍ଦ",
    messages: "ବାର୍ତ୍ତା",
    notifications: "ବିଜ୍ଞପ୍ତି",
    payments: "ପେମେଣ୍ଟ",
    profile: "ପ୍ରୋଫାଇଲ",
    settings: "ସେଟିଂସ",
    services: "ସେବା",
    reviews: "ସମୀକ୍ଷା",
    wallet: "ୱାଲେଟ",
    analytics: "ଆନାଲିଟିକ୍ସ",
    helpSupport: "ସହାୟତା ଓ ସମର୍ଥନ",
    logOut: "ଲଗ୍ ଆଉଟ୍",
    logout: "ଲଗ୍ ଆଉଟ୍",
    customerAccount: "ଗ୍ରାହକ ଖାତା",
    vendorAccount: "ଭେଣ୍ଡର ଖାତା",
    search: "ଖୋଜନ୍ତୁ...",
    searchBookings: "ବୁକିଂ ଖୋଜନ୍ତୁ...",
    settingsDescription: "ଆପ୍ ରୂପ, ଭାଷା, ଆଲର୍ଟ ଓ ଖାତା ଆକ୍ସେସ ପରିଚାଳନା କରନ୍ତୁ.",
    appSettings: "ଆପ୍ ସେଟିଂସ",
    darkTheme: "ଡାର୍କ ଥିମ",
    appLanguage: "ଆପ୍ ଭାଷା",
    audioLanguage: "ଅଡିଓ ଭାଷା",
    supportLanguage: "ସପୋର୍ଟ ଭାଷା",
    orderAlertSound: "ଅର୍ଡର ଆଲର୍ଟ ସାଉଣ୍ଡ",
    testAlertSound: "ଆଲର୍ଟ ସାଉଣ୍ଡ ଟେଷ୍ଟ",
    resetSettings: "ସେଟିଂସ ରିସେଟ",
    settingsSaved: "ସେଟିଂସ ସେଭ୍ ହେଲା.",
    settingsReset: "ସେଟିଂସ ରିସେଟ ହେଲା.",
    helpTitle: "ସହାୟତା ଓ ସମର୍ଥନ",
    helpDescription: "ବୁକିଂ, ପେମେଣ୍ଟ କିମ୍ବା ଖାତା ସହାୟତା ପାଇଁ BookMyEvent ସପୋର୍ଟ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ.",
    phone: "ଫୋନ",
    email: "ଇମେଲ",
    totalBookings: "ମୋଟ ବୁକିଂ",
    activeOrders: "ସକ୍ରିୟ ଅର୍ଡର",
    reviewsGiven: "ଦିଆଯାଇଥିବା ସମୀକ୍ଷା",
    browseVendors: "ଭେଣ୍ଡର ଦେଖନ୍ତୁ",
    hi: "ନମସ୍କାର",
    customer: "ଗ୍ରାହକ",
    vendor: "ଭେଣ୍ଡର",
    yourOrders: "ଆପଣଙ୍କ ଅର୍ଡର",
    viewAll: "ସବୁ ଦେଖନ୍ତୁ",
    loadingOrders: "ଅର୍ଡର ଲୋଡ୍ ହେଉଛି...",
    noOrdersDashboard: "ଏଯାବତ୍ କୌଣସି ଅର୍ଡର ନାହିଁ. ଭେଣ୍ଡର ବୁକ୍ କରି ଏଠାରେ ଦେଖନ୍ତୁ.",
    recommendedVendors: "ସୁପାରିଶ ଭେଣ୍ଡର",
    myOrders: "ମୋ ଅର୍ଡର",
    ordersDescription: "ବୁକିଂ ଅନୁରୋଧ, ନିଶ୍ଚିତକରଣ ଓ ବାକି ପେମେଣ୍ଟ ଟ୍ରାକ୍ କରନ୍ତୁ.",
    unableLoadOrders: "ଅର୍ଡର ଲୋଡ୍ ହେଲା ନାହିଁ.",
    vendorContactShared: "ପୂରା ପେମେଣ୍ଟ ପରେ ଭେଣ୍ଡର ସମ୍ପର୍କ ସେୟାର କରାଯାଇଛି",
    remainingDue: "ବାକି ପେମେଣ୍ଟ",
    vendorAcceptedPay48: "ଭେଣ୍ଡର ଆପଣଙ୍କ ଅନୁରୋଧ ଗ୍ରହଣ କରିଛନ୍ତି. ଏବେ ବାତିଲ୍ ବନ୍ଦ; 48 ଘଣ୍ଟା ଭିତରେ ପେମେଣ୍ଟ କରନ୍ତୁ, ନହେଲେ ଆଡଭାନ୍ସ ନନ୍-ରିଫଣ୍ଡେବଲ୍ ହେବ.",
    timeLeft: "ବାକି ସମୟ",
    payRemaining: "ବାକି ପେମେଣ୍ଟ କରନ୍ତୁ",
    withRazorpay: "Razorpay ସହିତ",
    cancelBeforeAccept: "ଭେଣ୍ଡର ଗ୍ରହଣ କରିବା ପୂର୍ବରୁ ଆପଣ ବାତିଲ୍ କରିପାରିବେ. ବାତିଲ୍ ପରେ ଆଡଭାନ୍ସ ରିଫଣ୍ଡ ଆରମ୍ଭ ହେବ.",
    selectCancellationReason: "ବାତିଲ୍ କାରଣ ବାଛନ୍ତୁ",
    close: "ବନ୍ଦ କରନ୍ତୁ",
    cancelling: "ବାତିଲ୍ ହେଉଛି...",
    confirmCancel: "ବାତିଲ୍ ନିଶ୍ଚିତ କରନ୍ତୁ",
    cancelBookingRefund: "ବୁକିଂ ବାତିଲ୍ ଓ ରିଫଣ୍ଡ",
    noOrders: "ଏଯାବତ୍ କୌଣସି ଅର୍ଡର ନାହିଁ.",
    bookedByMistake: "ଭୁଲରେ ବୁକ୍ ହୋଇଛି",
    eventDateChanged: "ଇଭେଣ୍ଟ ତାରିଖ ବଦଳିଲା",
    foundAnotherVendor: "ଅନ୍ୟ ଭେଣ୍ଡର ମିଳିଲା",
    budgetIssue: "ବଜେଟ୍ ସମସ୍ୟା",
    noLongerRequired: "ଆଉ ଆବଶ୍ୟକ ନାହିଁ",
    expired: "ସମାପ୍ତ",
    favoritesDescription: "ଦ୍ରୁତ ବୁକିଂ ପାଇଁ ସେଭ୍ କରାଯାଇଥିବା ଭେଣ୍ଡର.",
    loadingFavorites: "ପସନ୍ଦ ଲୋଡ୍ ହେଉଛି...",
    remove: "ହଟାନ୍ତୁ",
    noFavorites: "ଏଯାବତ୍ କୌଣସି ପସନ୍ଦ ନାହିଁ. ଭେଣ୍ଡର ଖୋଲି ହାର୍ଟ ବଟନ୍ ରୁ ସେଭ୍ କରନ୍ତୁ.",
    messagesDescription: "ଏଡମିନ୍ କୁ ସିଧା ସପୋର୍ଟ ବାର୍ତ୍ତା ପଠାନ୍ତୁ.",
    messageToAdmin: "ଏଡମିନ୍ କୁ ବାର୍ତ୍ତା",
    writeQuestion: "ଆପଣଙ୍କ ପ୍ରଶ୍ନ କିମ୍ବା ସମସ୍ୟା ଲେଖନ୍ତୁ...",
    sending: "ପଠାଯାଉଛି...",
    sendMessage: "ବାର୍ତ୍ତା ପଠାନ୍ତୁ",
    messageSent: "ବାର୍ତ୍ତା ଏଡମିନ୍ କୁ ପଠାଗଲା.",
    unableSendMessage: "ବାର୍ତ୍ତା ପଠାଯାଇ ପାରିଲା ନାହିଁ.",
    notificationsDescription: "ବୁକିଂ ଓ ପେମେଣ୍ଟ ଅପଡେଟ୍ ଏଠାରେ ଦେଖାଯିବ.",
    loadingNotifications: "ବିଜ୍ଞପ୍ତି ଲୋଡ୍ ହେଉଛି...",
    noNotifications: "ଏଯାବତ୍ କୌଣସି ବିଜ୍ଞପ୍ତି ନାହିଁ.",
    paymentsDescription: "ଆଡଭାନ୍ସ, ବାକି ଓ ରିଫଣ୍ଡ ରେକର୍ଡ.",
    loadingPayments: "ପେମେଣ୍ଟ ଲୋଡ୍ ହେଉଛି...",
    noPayments: "ଏଯାବତ୍ କୌଣସି ପେମେଣ୍ଟ ନାହିଁ.",
    updateCustomerDetails: "ଗ୍ରାହକ ବିବରଣୀ ଓ ପ୍ରୋଫାଇଲ ଫଟୋ ଅପଡେଟ୍ କରନ୍ତୁ.",
    updateDp: "DP ଅପଡେଟ୍",
    captureProfilePhoto: "ଲାଇଭ୍ ପ୍ରୋଫାଇଲ ଫଟୋ କ୍ୟାପଚର କରି ସେଭ୍ କରନ୍ତୁ.",
    retake: "ପୁଣି ନିଅନ୍ତୁ",
    savePhoto: "ଫଟୋ ସେଭ୍",
    saving: "ସେଭ୍ ହେଉଛି...",
    saveProfile: "ପ୍ରୋଫାଇଲ ସେଭ୍",
    name: "ନାମ",
    phoneLabel: "ଫୋନ",
    profileSaved: "ପ୍ରୋଫାଇଲ ସଫଳତାର ସହିତ ସେଭ୍ ହେଲା.",
    profilePhotoUpdated: "ପ୍ରୋଫାଇଲ ଫଟୋ ଅପଡେଟ୍ ହେଲା.",
    unableSaveProfile: "ପ୍ରୋଫାଇଲ ସେଭ୍ ହେଲା ନାହିଁ.",
    unableUpdatePhoto: "ପ୍ରୋଫାଇଲ ଫଟୋ ଅପଡେଟ୍ ହେଲା ନାହିଁ.",
  },
}

export const t = (language, key) => dashboardText[language]?.[key] || dashboardText.en[key] || key

export const playOrderAlertSound = (soundValue) => {
  const sound = soundOptions.find((item) => item.value === soundValue) || soundOptions[0]
  if (!sound.frequency) return

  const AudioContext = window.AudioContext || window.webkitAudioContext
  if (!AudioContext) return

  const context = new AudioContext()
  const oscillator = context.createOscillator()
  const gain = context.createGain()
  oscillator.type = sound.value === "urgent" ? "square" : "sine"
  oscillator.frequency.setValueAtTime(sound.frequency, context.currentTime)
  gain.gain.setValueAtTime(0.001, context.currentTime)
  gain.gain.exponentialRampToValueAtTime(0.18, context.currentTime + 0.02)
  gain.gain.exponentialRampToValueAtTime(0.001, context.currentTime + 0.45)
  oscillator.connect(gain)
  gain.connect(context.destination)
  oscillator.start()
  oscillator.stop(context.currentTime + 0.5)
}
